"""
MedScholar Literature Survey Agent

An AI agent specialized in conducting comprehensive literature surveys
for healthcare and medical research topics.
"""

from typing import Optional
from pydantic import Field

from app.agent.toolcall import ToolCallAgent
from app.config import config
from app.prompt.healthcare import NEXT_STEP_PROMPT, SYSTEM_PROMPT
from app.tool import Terminate, ToolCollection, WebSearch, StrReplaceEditor, Bash


class MedScholarAgent(ToolCallAgent):
    """
    A specialized agent for conducting healthcare and medical literature surveys.

    This agent extends ToolCallAgent with tools specifically suited for:
    - Searching medical and healthcare literature
    - Analyzing research papers and clinical studies
    - Synthesizing findings into comprehensive reports
    - Identifying research gaps and trends

    The agent maintains scientific rigor by prioritizing peer-reviewed sources,
    properly citing references, and distinguishing between different levels of evidence.
    """

    name: str = "MedScholar_Agent"
    description: str = (
        "A specialized AI agent for conducting comprehensive literature surveys "
        "in healthcare and medical research, with capabilities for searching, "
        "analyzing, and synthesizing scientific literature."
    )

    system_prompt: str = SYSTEM_PROMPT.format(directory=config.workspace_root)
    next_step_prompt: str = NEXT_STEP_PROMPT

    # Configure execution parameters
    max_observe: int = 15000  # Maximum characters to observe from tool outputs
    max_steps: int = 25  # Maximum number of steps for comprehensive surveys

    # Tool collection tailored for literature surveys
    available_tools: ToolCollection = Field(
        default_factory=lambda: ToolCollection(
            WebSearch(
                # Configure for academic/medical searches
                max_results=10,  # Get more results for comprehensive surveys
                fetch_webpage_content=True,  # Retrieve full content for analysis
            ),
            StrReplaceEditor(),  # For creating and editing survey report files
            Bash(),  # For any system operations needed
            Terminate(),  # Signal completion of the survey
        )
    )

    class Config:
        arbitrary_types_allowed = True
        extra = "allow"

    async def run(self, user_input: str, **kwargs) -> None:
        """
        Execute a healthcare literature survey based on user input.

        Args:
            user_input: The research question or topic to survey
            **kwargs: Additional parameters for customization
        """
        # Enhance the user input with context about literature survey expectations
        enhanced_input = f"""
Please conduct a comprehensive literature survey on the following topic:

{user_input}

Your survey should:
1. Search for relevant recent research, systematic reviews, and clinical guidelines
2. Analyze the quality and relevance of sources found
3. Synthesize key findings, identifying themes, trends, and gaps
4. Distinguish between different levels of evidence (systematic reviews, RCTs, observational studies)
5. Provide proper citations with URLs when available
6. Save the final survey report to a file in the workspace

Focus on peer-reviewed sources and authoritative medical literature.
"""

        return await super().run(enhanced_input, **kwargs)

    def _format_survey_report(
        self,
        topic: str,
        findings: list,
        synthesis: str,
        references: list
    ) -> str:
        """
        Helper method to format a literature survey report.

        Args:
            topic: The research topic surveyed
            findings: List of key findings from the literature
            synthesis: Synthesized analysis and conclusions
            references: List of references with citations

        Returns:
            Formatted markdown report
        """
        report = f"""# Healthcare Literature Survey: {topic}

## Executive Summary
{synthesis}

## Key Findings

"""
        for i, finding in enumerate(findings, 1):
            report += f"{i}. {finding}\n\n"

        report += """
## Evidence Quality Assessment
[To be filled based on source analysis]

## Research Gaps and Future Directions
[To be filled based on literature analysis]

## References

"""
        for i, ref in enumerate(references, 1):
            report += f"{i}. {ref}\n"

        report += f"""
---
*Report generated by MedScholar Literature Survey Agent*
*Date: {self._get_current_date()}*
"""
        return report

    def _get_current_date(self) -> str:
        """Get current date for report metadata."""
        from datetime import datetime
        return datetime.now().strftime("%Y-%m-%d")
